### ISSUE TITLE
Replace OpenGL and Sodium for the more modern vulkan renderer

### ISSUE THREAD

**Issue by Mathewthemvp** [ragedriver/Minecraft-Optimization-Pack#3]
replace the old opengl and sodium with the new modern standard vulkan renderer which can BE found inhere: https://www.curseforge.com/minecraft/mc-mods/vulkanmod
fps is way better using vulkan as a rendering engine instead of sodium or other alternatives atleast make a version with vulkan like an beta or something please

**Comment by TherionRO** [comment]
I already tested out Vulkan as the render engine for Optimization Pack some time ago. It is unstable on Optimization Pack currently and the performance gain is not that high for now.

**Comment by ragedriver** [comment]
I already tested out Vulkan as the render engine for Optimization Pack some time ago. It is unstable on Optimization Pack currently and the performance gain is not that high for now.
