### ISSUE TITLE
FPS Counter not working on both alpha builds.

### ISSUE THREAD

**Issue by DevExCraft** [ragedriver/Minecraft-Optimization-Pack#4]
I just tested both alpha builds and from my testings the fps counter is broken(only the f3 menu works).this is due to exordium as it basically limits the fps of every hud except F3,and it limits FPS Reducer,please whitelist fpsreducer from exordium as this fixes the issue.

**Comment by ragedriver** [comment]
Hey.I am aware of this issue.Will do some more testing for this

**Comment by ragedriver** [comment]
Issue fixed in OP 3.0 !
